SET search_path TO eurder_project;

CREATE TABLE customer
(
    ID           VARCHAR(36)  NOT NULL,
    FIRST_NAME   VARCHAR(100) NOT NULL,
    LAST_NAME    VARCHAR(100) NOT NULL,
    EMAIL        VARCHAR(100) NOT NULL,
    ADDRESS      VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(40)  NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);