CREATE TABLE EURDER
(
    ID VARCHAR(36) NOT NULL,
    FK_CUSTOMER_ID VARCHAR(36) NOT NULL,
    TOTAL_PRICE FLOAT NOT NULL,
    CONSTRAINT PK_EURDER PRIMARY KEY (ID),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (FK_CUSTOMER_ID) REFERENCES CUSTOMER (ID)
);
CREATE TABLE ITEM_GROUP
(
    ID VARCHAR(36) NOT NULL,
    FK_ITEM_ID VARCHAR(36) NOT NULL,
    FK_EURDER_ID VARCHAR(36) NOT NULL,
    AMOUNT INTEGER NOT NULL,
    PRICE FLOAT NOT NULL,
    SHIPPING_DATE DATE NOT NULL,
    CONSTRAINT PK_ITEM_GROUP PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_ID FOREIGN KEY (FK_ITEM_ID) REFERENCES ITEM (ID),
    CONSTRAINT FK_EURDER_ID FOREIGN KEY (FK_EURDER_ID) REFERENCES EURDER (ID)
);